### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by mortation** [pro-celigo/lib-netsuite-servicemgr#14]
Is there any documentation anywhere?  I can't seem to find a single example of setting the passport credentials and opening a connection.  I tried replicating what I saw in the unit tests but it didnt seem to work.  I cant cast a SuiteTalk Passport to a passportprovider.  Any guidance and support would be appreciated, thanks!

**Comment by sameera** [comment]
@mortation
The best source would be the unit tests. For example:
https://github.com/pro-celigo/lib-netsuite-servicemgr/blob/master/Celigo.ServiceManager.NetSuite/test/UnitTest/NetSuiteClientTests.cs

**Comment by mortation** [comment]
Thanks for the response, that was my attempt, however in TestConfigurtion
 this.TokenPassportProvider = new EnvVariableTokenPassportProvider(); 
 lead me to EnvVariablePassportProvider which in there shows that it returns a new PassPort and when I tried to do things in that order it gave a casting error for PassPort to PassportProvider.  I'm probably missing something obvious at this point but can't seem to see it.  Thanks again!

**Comment by sameera** [comment]
If you see the interface [1], CreateClient should be able to take a Passport or a PassportProvider. 
So you can pass the EnvVariablePassportProvider there.

Can you post your code for me to take a look? 
Apologies in advance if i don't get back yo yiu immediately. Im away form the computer and am not sure when id get to check this again in the next 8hrs.

[1] https://github.com/pro-celigo/lib-netsuite-servicemgr/blob/master/Celigo.ServiceManager.NetSuite/src/ClientFactory.cs

**Comment by mortation** [comment]
Here is the current state of the test code:

private TokenPassport _tokenPassport;
private readonly INetSuiteClient _client;
private ITokenPassportProvider _tokenPassportProvider;

public ItemRepository()
        {
            if (_tokenPassport == null)
            {
                string consumerSecret = "STRING";
                string consumerKey = "STRING";

                var passportBuilder = new DefaultTokenPassportBuilder(consumerKey, consumerSecret);

                string token = "STRING";
                string tokenSecret = "STRING";
                string account = "STRING";

                _tokenPassport = passportBuilder.Build(account, token, tokenSecret);
            }

            var clientFactory = new ClientFactory("APPIDSTRING");
            _client = clientFactory.CreateClient(_tokenPassport);
            _client.Endpoint.Address = new System.ServiceModel.EndpointAddress("https://XXXXXXXX.suitetalk.api.netsuite.com/services/NetSuitePort_2018_2");
            var binding = (BasicHttpBinding)_client.Endpoint.Binding;
Task<GetServerTimeResult> task = System.Threading.Tasks.Task.Run<GetServerTimeResult>(async () => await _client.getServerTimeAsync());

throw new NotImplementedException(task.Result.ToString());
        }

**Comment by sameera** [comment]
I think what you are trying to do is avoid having to build the `_tokenPassport` every time and cache it for subsequent calls. This will not work as the `tokenPassport` *must* be regenerated on each call. TBA security depends on a nonce value that's unique for each call, and a timestamp that's current. the `passportBuilder.Build` method takes care of this for you. 
A cached `tokenPassport` will always be out dated and will cause NetSuite to return `Invalid Login Attempt` error. This is why the `CreateClient` method does not accept a `TokenPassport` as a parameter (why you are getting a casting error); while it accepts a `Passport` (for basic credentials based login).

So, what you should be doing is caching the configured `passportBuilder` instance and pass it to each call of `CreateClient`.

**Comment by mortation** [comment]
Here is what I have done after some sleep:

NetSuitePassPortProvider.cs:
    class NetSuitePassPortProvider : ITokenPassportProvider
    {
        private readonly object _tokenLock = new object();
        private TokenPassport _tokenPassport;

        public TokenPassport GetTokenPassport()
        {
            if (_tokenPassport == null)
                lock (_tokenLock)
                {
                    if (_tokenPassport == null)
                    {
                        string consumerSecret = "STRING";
                        string consumerKey = "STRING";

                        var passportBuilder = new DefaultTokenPassportBuilder(consumerKey, consumerSecret);

                        string token = "STRING";
                        string tokenSecret = "STRING";
                        string account = "STRING";

                        _tokenPassport = passportBuilder.Build(account, token, tokenSecret);
                    }
                }
            return _tokenPassport;
        }

        public NetSuitePassPortProvider()
        {

        }
    }

NetSuiteConfiguration.cs:
class NetSuiteConfiguration
    {
        public string ApplicationId { get; set; }
        public IPassportProvider PassportProvider { get; set; }
        public ITokenPassportProvider TokenPassportProvider { get; set; }

        public NetSuiteConfiguration()
        {
            this.ApplicationId = "STRING";
            //this.PassportProvider = new EnvVariablePassportProvider();
            this.TokenPassportProvider = new NetSuitePassPortProvider();
        }
    }

In my test call I do:
public Test()
        {
            var config = new NetSuiteConfiguration();
            var clientFactory = new ClientFactory(config.ApplicationId);

            _client = clientFactory.CreateClient(config.TokenPassportProvider);
            var binding = (BasicHttpBinding)_client.Endpoint.Binding;

Task<GetServerTimeResult> task = System.Threading.Tasks.Task.Run<GetServerTimeResult>(async () => await _client.getServerTimeAsync());

            throw new NotImplementedException(task.Result.ToString());
        }

And now I get the XML error the other issue posted here was about.  I saw it said to use IConfiguration to set the domain URL but I have not seen an example of that yet, do you have one?  Thank you for your help!

**Comment by mortation** [comment]
I updated the Public test to include:

var config = new NetSuiteConfiguration();
            var clientFactory = new ClientFactory(config.ApplicationId);
            ConfigurationProvider configProvider = new ConfigurationProvider() { DataCenter = new DataCenterConfiguration("https://XXXXXXX.suitetalk.api.netsuite.com/services/NetSuitePort_2018_2") };

            _client = clientFactory.CreateClient(config.TokenPassportProvider, configProvider);
            var binding = (BasicHttpBinding)_client.Endpoint.Binding;

But still get the error:
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (The content type text/html; charset=utf-8 of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 431 bytes of the response were: '<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><soapenv:Fault><faultcode>soapenv:Server.userException</faultcode><faultstring>no API version found for 2018_2/services/NetSuitePort_2018_2</faultstring></soapenv:Fault></soapenv:Body></soapenv:Envelope>'.)
  Source=System.Private.CoreLib
  StackTrace:
 ETC...

**Comment by mortation** [comment]
I tried switching from a tokenpassport to regular passport using creds and it works.

**Comment by sameera** [comment]
@mortation 
Can you try fixing the following line as shown:
```
            ConfigurationProvider configProvider = new ConfigurationProvider() { DataCenter = new DataCenterConfiguration("https://XXXXXXX.suitetalk.api.netsuite.com") };
```

**Comment by mortation** [comment]
That solved that last problem, thanks for the help!

**Comment by sameera** [comment]
Glad to hear that @mortation
