### ISSUE TITLE
Documents?

### ISSUE THREAD

**Issue by camerontbelt** [pro-celigo/lib-netsuite-servicemgr#18]
Im looking for documents on how to use this and I cant find anything here or on Celigo's website? 

Is this part of a paid service from Celigo or is this free to use by anyone?

**Comment by sameera** [comment]
It's free for all. But unfortunately, at the moment I'm the only person available to maintain this and i do so along with multiple other projects. 
Sorry about the lack of documentation. There's a bit of information here https://sameera.tech/
If you have specific questions, I can answer as well.

**Comment by sameera** [comment]
Closing as specific questions were answered on another issue thread.
