### ISSUE TITLE
netstandard support

### ISSUE THREAD

**Issue by jeanft** [pro-celigo/lib-netsuite-servicemgr#20]
Why is it now in .net core rather than .net standard? This is a big limitation for us as we plan to develop soon in Xamarin ans Xamarin only support .net standard. We also need to use the new Three-Step Authorization.
And we really enjoy using your lib.

Thanks a lot

**Comment by sameera** [comment]
@jeanft we moved to .net core to take advantage of some core 2.2 features unavailable to .net standard 2.0
Give me sometime to do a check on whether we can work around them and get back on standard 2.0

**Comment by jeanft** [comment]
Take a look at the branch netstandard from my fork (PyxisStudio)
Just changing to netstandard and everythings build successfully.
What feature from core you want?

Jeff

**Comment by sameera** [comment]
Hey Jeff,
You are right, it no longer has issues compiling with .NET Standard 2.0. I believe we were running in to issues with some pre-release nuget packages that were later updated. We are doing a v4.2 targeting .net standard 2.0

**Comment by jeanft** [comment]
Thank you!

**Comment by jeanft** [comment]
I'll wait the Nuget release.

**Comment by sameera** [comment]
Jeff
Version 4.2 is nuget now
