### ISSUE TITLE
[Question] Newer WSDL version support

### ISSUE THREAD

**Issue by dantheman999301** [pro-celigo/lib-netsuite-servicemgr#26]
I was just wondering generally how often this library is going to be updated for the different WSDL versions? 

At the moment it is targeting the 2018.2 and 2019.2 has been released recently. Not sure how quickly they are deprecated (or if they are at all).

Obviously I could fork and update the underlying WSDL if I needed to update, but was just a general question.

**Comment by dantheman999301** [comment]
That's all fine, as I say it was more of a general question if anything. Trying to work out how often we should be checking for updates internally more than anything else.

Do you know how often Netsuite deprecates these endpoints? I've had a look around but searching for anything Netsuite related just brings up massive PDFs. They certainly don't make information easy to find.

**Comment by sameera** [comment]
A NetSuite endpoint is available up to 15 subsequent releases. However, NetSuite's current recommendation is that you are at least on 2016.2.
You can find this information on the NetSuite Platform Guide under the section "Support for Existing WSDL versions"
https://docs.oracle.com/cloud/latest/netsuitecs_gs/NSTWP/NSTWP.pdf

**Comment by dontana** [comment]
Hi!  We are using your code for an API we built and it is working great; however, we have a need for the 2019.2 WSDL version.  There are payment fields available in that WSDL that are not available in earlier version, such as "PaymentOptions".  I would like to request support for that version, or greater.  The fields we need are critical to the project we are working on.  I am hoping you can update the code.  Thanks!

**Comment by sameera** [comment]
@dontana 
We can take it up. Do you have a timeline that you'd like to see this by?

**Comment by sameera** [comment]
@dontana 
We have pushed out a 6.0 package that's built for 2019.2 WSDL. 
Unfortunately, on our side we don't have a lot of bandwidth to do much testing on it at the moment, beyond the limited unit testing.
Please do get back to us if you run in to issues.

`Install-Package Celigo.ServiceManager.NetSuite -Version 6.0.0`
