### ISSUE TITLE
How to retrieve Inventory Worksheets via SuiteTalk?

### ISSUE THREAD

**Issue by efeker** [pro-celigo/lib-netsuite-servicemgr#29]
Hello,
I have been trying to find a way to retrieve Inventory Worksheets via SuiteTalk however that record type does not exist. Does anybody know an alternative way?

Thanks

**Comment by sameera** [comment]
Hi @efeker 
Inventory Worksheets are not a supported record type in Web Services (see the list of supported transaction record types here: https://YOURNSACCTNUMBER.app.netsuite.com/app/help/helpcenter.nl?fid=chapter_N3657735.html)

So you would probably have to resort to doing multiple Inventory Adjustments for this purpose.
