### ISSUE TITLE
Help with connecting to Sandbox

### ISSUE THREAD

**Issue by camerontbelt** [pro-celigo/lib-netsuite-servicemgr#37]
Can someone help me understand how to connect to the sandbox account? 

I've tried the following 

```
            var passportProvider = new PassportProvider(passport);
            var a = new DataCenterConfiguration(EndPointType.Sandbox);
            var b = new ConfigurationProvider {DataCenter = a};
            NetSuite = new ClientFactory(ApplicationId).CreateClient(passportProvider, b);
```

But received the following error

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at CorporateWebApp.Test.Unit_Tests.Core.BusinessRules.Netsuite.PostInvoiceTest.Test() in C:\Users\cbelt\source\repos\Corporate_Website\CorporateWebApp.Test\Unit Tests\Core\BusinessRules\Netsuite\PostInvoiceTest.cs:line 22

Inner Exception 1:
ArgumentException: The provided URI scheme 'http' is invalid; expected 'https'.
Parameter name: via
```

**Comment by sameera** [comment]
@camerontbelt 
You only need to provide the sandbox account number  (generally in the form of something like `12345_sb1`).
Given that you already have set the sandbox account number in the passport, following should work:
```
 NetSuite = new ClientFactory(ApplicationId).CreateClient(passport);
```

**Comment by sameera** [comment]
On a side note: We should get rid of the DataCenterConfig. It is no longer the right approach as NetSuite recommends that we use account specific URLs rather than DC URLs.

**Comment by camerontbelt** [comment]
@sameera Now I get the following error.

`Could not determine customer compid`

**Comment by sameera** [comment]
@camerontbelt it should be `_SB1` instead of `-SB1`.

**Comment by camerontbelt** [comment]
> @camerontbelt it should be `_SB1` instead of `-SB1`.

Ah thank you, I think I tried that with lower case 'sb' and it didnt work, so it has to be upper case and an underscore.

**Comment by sameera** [comment]
The case wouldn't matter actually (the library internally converts the case where needed). But the underscore: yes.
