### ISSUE TITLE
Using a token based passport?

### ISSUE THREAD

**Issue by camerontbelt** [pro-celigo/lib-netsuite-servicemgr#39]
I cant find where you have a unit test or example of using a token based passport to create a netsuite client.

**Comment by sameera** [comment]
There isn't much but following should serve as a simple starting point:

[TokenBasedClientTests](https://github.com/pro-celigo/lib-netsuite-servicemgr/blob/master/Celigo.ServiceManager.NetSuite/test/UnitTest/TokenBasedClientTests.cs)

**Comment by camerontbelt** [comment]
> There isn't much but following should serve as a simple starting point:
> 
> [TokenBasedClientTests](https://github.com/pro-celigo/lib-netsuite-servicemgr/blob/master/Celigo.ServiceManager.NetSuite/test/UnitTest/TokenBasedClientTests.cs)

The problem with this unit test is it doesnt actually help in any way. 

I have a key and secret, that unit test you linked doesnt show me how to set any of that up. The problem im facing is that when I try to do it the way that makes sense, I get an error from the server telling me theres malformed syntax. And since you dont actually have code that shows me how to set up the token passport I cant know for sure if its my code or just a bad key/secret pair. 

`            
var passport = new TokenPassport
            {
                account = account,
                consumerKey = key,
                token = secret,
                signature = new TokenPassportSignature
                {
                    algorithm = "HMAC-SHA1"
                }
            };
            var passportProvider = new TokenPassportProvider(passport);
            NetSuite = new ClientFactory(Constants.ApplicationId).CreateClient(passportProvider);
`

Im looking for something like this but that actually works. TokenPassportProvider is a class that implements ITokenPassportProvider.

**Comment by sameera** [comment]
@camerontbelt 
in the unit test, we are using the (`EnvVariableTokenPassportProvider`)[https://github.com/pro-celigo/lib-netsuite-servicemgr/blob/master/PassportProviders.EnvVariables/src/EnvVariableTokenPassportProvider.cs]. 
You will see on (this line)[https://github.com/pro-celigo/lib-netsuite-servicemgr/blob/master/PassportProviders.EnvVariables/src/EnvVariableTokenPassportProvider.cs#L46] that we are using the (`DefaultTokenPassportBuilder`)[https://github.com/pro-celigo/lib-netsuite-servicemgr/blob/master/Celigo.SuiteTalk/src/TokenPassportBuilder.cs#L22] to generate a `TokenPassport` that has a computed signature.

The `TokenPassport` unlike the `Passport` used for basic credentials (username/password) login cannot be a static value as the signature needs to be recalculated at each requests to NetSuite as the `nonce` and `timestamp` values will always be different.

(The line)[https://github.com/pro-celigo/lib-netsuite-servicemgr/blob/master/PassportProviders.EnvVariables/src/EnvVariableTokenPassportProvider.cs#L46]
` _tokenPassport = passportBuilder.Build(account, token, tokenSecret);`
is probably what you are missing in your `TokenPassportProvider.GetTokenPassport()` method.
