### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by dmelinosky** [pro-celigo/lib-netsuite-servicemgr#40]
Any plans to support the 2021.1 api with the credential changes that seem to be required?  Looks like a token based authentication will be required.  Does the library already support that?

**Comment by sameera** [comment]
@dmelinosky If you are concerned about SHA1 deprecation, the library already uses SHA256.
Internally, we do not have near-term plans to move to 2021.1 as we don't have an immediate use case.

**Comment by dmelinosky** [comment]
I was asking because of an email that was passed down to me stating 

"As of the 2020.1 endpoint, the ssoLogin operation is no longer working.  For SOAP web services you must use Token-based Authentication instead".

**Comment by sameera** [comment]
Yes, in that case it's already covered in the lib.

If you are interested in SSO with NetSuite, [my blog post on 3-Step-Authentication](https://sameera.tech/2019/10/08/authorizing-suitetalk-web-services-apps-with-netsuites-three-step-authorization-flow/) might help.
