### ISSUE TITLE
HTTPDelete support

### ISSUE THREAD

**Issue by sjd2021** [pro-celigo/lib-netsuite-servicemgr#44]
Can you support deletes (versus just puts, patches, posts, and gets) with the `RestClient`? I also think that there should be an overload of sorts which just takes the HttpMethod enum. That's how many clients such as the base `HttpClient.SendAsync` (vs `PostAsync`, etc.) methods work, so I think it'd be consistent and easy to implement.

**Comment by sameera** [comment]
@sjd2021
@somenathmaji added support for HTTP Delete. Since we now have all the main methods covered, we thought we'd stop at that.

**Comment by sjd2021** [comment]
> @sjd2021
> @somenathmaji added support for HTTP Delete. Since we now have all the main methods covered, we thought we'd stop at that.

Thank you! May I request a release so that a nuget push is initiated or is this too small for an official release?
